version: '3.9'
services:
  UserData:
    build:
      context: .
      dockerfile: Dockerfile
    image: user-data:v1
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGERS_DB_NAME=user_data
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=qwerty
    networks:
      - backend
    depends_on:
      - postgres

  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  backend:

volumes:
  db-data:
    driver: local